/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.sample.pet.service.service.base;

import com.dogoo.sample.pet.service.model.AnimalGroupEntry;
import com.dogoo.sample.pet.service.service.AnimalGroupEntryLocalService;
import com.dogoo.sample.pet.service.service.AnimalGroupEntryLocalServiceUtil;
import com.dogoo.sample.pet.service.service.persistence.AnimalGroupEntryPersistence;
import com.dogoo.sample.pet.service.service.persistence.AnimalTagEntryPersistence;
import com.dogoo.sample.pet.service.service.persistence.DogEntryPersistence;
import com.dogoo.sample.pet.service.service.persistence.PetEntryPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the animal group entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dogoo.sample.pet.service.service.impl.AnimalGroupEntryLocalServiceImpl}.
 * </p>
 *
 * @author khoavu
 * @see com.dogoo.sample.pet.service.service.impl.AnimalGroupEntryLocalServiceImpl
 * @generated
 */
public abstract class AnimalGroupEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AnimalGroupEntryLocalService, AopService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>AnimalGroupEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>AnimalGroupEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the animal group entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnimalGroupEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param animalGroupEntry the animal group entry
	 * @return the animal group entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AnimalGroupEntry addAnimalGroupEntry(
		AnimalGroupEntry animalGroupEntry) {

		animalGroupEntry.setNew(true);

		return animalGroupEntryPersistence.update(animalGroupEntry);
	}

	/**
	 * Creates a new animal group entry with the primary key. Does not add the animal group entry to the database.
	 *
	 * @param animalGroupId the primary key for the new animal group entry
	 * @return the new animal group entry
	 */
	@Override
	@Transactional(enabled = false)
	public AnimalGroupEntry createAnimalGroupEntry(long animalGroupId) {
		return animalGroupEntryPersistence.create(animalGroupId);
	}

	/**
	 * Deletes the animal group entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnimalGroupEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param animalGroupId the primary key of the animal group entry
	 * @return the animal group entry that was removed
	 * @throws PortalException if a animal group entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AnimalGroupEntry deleteAnimalGroupEntry(long animalGroupId)
		throws PortalException {

		return animalGroupEntryPersistence.remove(animalGroupId);
	}

	/**
	 * Deletes the animal group entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnimalGroupEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param animalGroupEntry the animal group entry
	 * @return the animal group entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public AnimalGroupEntry deleteAnimalGroupEntry(
		AnimalGroupEntry animalGroupEntry) {

		return animalGroupEntryPersistence.remove(animalGroupEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return animalGroupEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			AnimalGroupEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return animalGroupEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.sample.pet.service.model.impl.AnimalGroupEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return animalGroupEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.sample.pet.service.model.impl.AnimalGroupEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return animalGroupEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return animalGroupEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return animalGroupEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public AnimalGroupEntry fetchAnimalGroupEntry(long animalGroupId) {
		return animalGroupEntryPersistence.fetchByPrimaryKey(animalGroupId);
	}

	/**
	 * Returns the animal group entry matching the UUID and group.
	 *
	 * @param uuid the animal group entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching animal group entry, or <code>null</code> if a matching animal group entry could not be found
	 */
	@Override
	public AnimalGroupEntry fetchAnimalGroupEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return animalGroupEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the animal group entry with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the animal group entry's external reference code
	 * @return the matching animal group entry, or <code>null</code> if a matching animal group entry could not be found
	 */
	@Override
	public AnimalGroupEntry fetchAnimalGroupEntryByExternalReferenceCode(
		long companyId, String externalReferenceCode) {

		return animalGroupEntryPersistence.fetchByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * @deprecated As of Cavanaugh (7.4.x), replaced by {@link #fetchAnimalGroupEntryByExternalReferenceCode(long, String)}
	 */
	@Deprecated
	@Override
	public AnimalGroupEntry fetchAnimalGroupEntryByReferenceCode(
		long companyId, String externalReferenceCode) {

		return fetchAnimalGroupEntryByExternalReferenceCode(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the animal group entry with the matching external reference code and company.
	 *
	 * @param companyId the primary key of the company
	 * @param externalReferenceCode the animal group entry's external reference code
	 * @return the matching animal group entry
	 * @throws PortalException if a matching animal group entry could not be found
	 */
	@Override
	public AnimalGroupEntry getAnimalGroupEntryByExternalReferenceCode(
			long companyId, String externalReferenceCode)
		throws PortalException {

		return animalGroupEntryPersistence.findByC_ERC(
			companyId, externalReferenceCode);
	}

	/**
	 * Returns the animal group entry with the primary key.
	 *
	 * @param animalGroupId the primary key of the animal group entry
	 * @return the animal group entry
	 * @throws PortalException if a animal group entry with the primary key could not be found
	 */
	@Override
	public AnimalGroupEntry getAnimalGroupEntry(long animalGroupId)
		throws PortalException {

		return animalGroupEntryPersistence.findByPrimaryKey(animalGroupId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			animalGroupEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AnimalGroupEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("animalGroupId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			animalGroupEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(AnimalGroupEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"animalGroupId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			animalGroupEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(AnimalGroupEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("animalGroupId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<AnimalGroupEntry>() {

				@Override
				public void performAction(AnimalGroupEntry animalGroupEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, animalGroupEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(AnimalGroupEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return animalGroupEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return animalGroupEntryLocalService.deleteAnimalGroupEntry(
			(AnimalGroupEntry)persistedModel);
	}

	@Override
	public BasePersistence<AnimalGroupEntry> getBasePersistence() {
		return animalGroupEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return animalGroupEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the animal group entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the animal group entries
	 * @param companyId the primary key of the company
	 * @return the matching animal group entries, or an empty list if no matches were found
	 */
	@Override
	public List<AnimalGroupEntry> getAnimalGroupEntriesByUuidAndCompanyId(
		String uuid, long companyId) {

		return animalGroupEntryPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of animal group entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the animal group entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of animal group entries
	 * @param end the upper bound of the range of animal group entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching animal group entries, or an empty list if no matches were found
	 */
	@Override
	public List<AnimalGroupEntry> getAnimalGroupEntriesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<AnimalGroupEntry> orderByComparator) {

		return animalGroupEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the animal group entry matching the UUID and group.
	 *
	 * @param uuid the animal group entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching animal group entry
	 * @throws PortalException if a matching animal group entry could not be found
	 */
	@Override
	public AnimalGroupEntry getAnimalGroupEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return animalGroupEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the animal group entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.sample.pet.service.model.impl.AnimalGroupEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of animal group entries
	 * @param end the upper bound of the range of animal group entries (not inclusive)
	 * @return the range of animal group entries
	 */
	@Override
	public List<AnimalGroupEntry> getAnimalGroupEntries(int start, int end) {
		return animalGroupEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of animal group entries.
	 *
	 * @return the number of animal group entries
	 */
	@Override
	public int getAnimalGroupEntriesCount() {
		return animalGroupEntryPersistence.countAll();
	}

	/**
	 * Updates the animal group entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect AnimalGroupEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param animalGroupEntry the animal group entry
	 * @return the animal group entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public AnimalGroupEntry updateAnimalGroupEntry(
		AnimalGroupEntry animalGroupEntry) {

		return animalGroupEntryPersistence.update(animalGroupEntry);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			AnimalGroupEntryLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		animalGroupEntryLocalService = (AnimalGroupEntryLocalService)aopProxy;

		_setLocalServiceUtilService(animalGroupEntryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return AnimalGroupEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return AnimalGroupEntry.class;
	}

	protected String getModelClassName() {
		return AnimalGroupEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = animalGroupEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		AnimalGroupEntryLocalService animalGroupEntryLocalService) {

		try {
			Field field =
				AnimalGroupEntryLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, animalGroupEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	protected AnimalGroupEntryLocalService animalGroupEntryLocalService;

	@Reference
	protected AnimalGroupEntryPersistence animalGroupEntryPersistence;

	@Reference
	protected AnimalTagEntryPersistence animalTagEntryPersistence;

	@Reference
	protected DogEntryPersistence dogEntryPersistence;

	@Reference
	protected PetEntryPersistence petEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}