/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.poc.upgradeservice.cat.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CatEntry service. Represents a row in the &quot;DG_UGS_CAT&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.poc.upgradeservice.cat.service.model.impl.CatEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.poc.upgradeservice.cat.service.model.impl.CatEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CatEntry
 * @generated
 */
@ProviderType
public interface CatEntryModel extends BaseModel<CatEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cat entry model instance should use the {@link CatEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this cat entry.
	 *
	 * @return the primary key of this cat entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cat entry.
	 *
	 * @param primaryKey the primary key of this cat entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this cat entry.
	 *
	 * @return the uuid of this cat entry
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this cat entry.
	 *
	 * @param uuid the uuid of this cat entry
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the cat ID of this cat entry.
	 *
	 * @return the cat ID of this cat entry
	 */
	public long getCatId();

	/**
	 * Sets the cat ID of this cat entry.
	 *
	 * @param catId the cat ID of this cat entry
	 */
	public void setCatId(long catId);

	/**
	 * Returns the name of this cat entry.
	 *
	 * @return the name of this cat entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this cat entry.
	 *
	 * @param name the name of this cat entry
	 */
	public void setName(String name);

	/**
	 * Returns the gender of this cat entry.
	 *
	 * @return the gender of this cat entry
	 */
	public boolean getGender();

	/**
	 * Returns <code>true</code> if this cat entry is gender.
	 *
	 * @return <code>true</code> if this cat entry is gender; <code>false</code> otherwise
	 */
	public boolean isGender();

	/**
	 * Sets whether this cat entry is gender.
	 *
	 * @param gender the gender of this cat entry
	 */
	public void setGender(boolean gender);

	/**
	 * Returns the dob of this cat entry.
	 *
	 * @return the dob of this cat entry
	 */
	public Date getDob();

	/**
	 * Sets the dob of this cat entry.
	 *
	 * @param dob the dob of this cat entry
	 */
	public void setDob(Date dob);

	/**
	 * Returns the category of this cat entry.
	 *
	 * @return the category of this cat entry
	 */
	public long getCategory();

	/**
	 * Sets the category of this cat entry.
	 *
	 * @param category the category of this cat entry
	 */
	public void setCategory(long category);

	@Override
	public CatEntry cloneWithOriginalValues();

}