/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.sample.pet.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AnimalGroupEntry service. Represents a row in the &quot;DG_ANIMALGROUP&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.sample.pet.service.model.impl.AnimalGroupEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.sample.pet.service.model.impl.AnimalGroupEntryImpl</code>.
 * </p>
 *
 * @author khoavu
 * @see AnimalGroupEntry
 * @generated
 */
@ProviderType
public interface AnimalGroupEntryModel
	extends BaseModel<AnimalGroupEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a animal group entry model instance should use the {@link AnimalGroupEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this animal group entry.
	 *
	 * @return the primary key of this animal group entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this animal group entry.
	 *
	 * @param primaryKey the primary key of this animal group entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this animal group entry.
	 *
	 * @return the uuid of this animal group entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this animal group entry.
	 *
	 * @param uuid the uuid of this animal group entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this animal group entry.
	 *
	 * @return the external reference code of this animal group entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this animal group entry.
	 *
	 * @param externalReferenceCode the external reference code of this animal group entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the animal group ID of this animal group entry.
	 *
	 * @return the animal group ID of this animal group entry
	 */
	public long getAnimalGroupId();

	/**
	 * Sets the animal group ID of this animal group entry.
	 *
	 * @param animalGroupId the animal group ID of this animal group entry
	 */
	public void setAnimalGroupId(long animalGroupId);

	/**
	 * Returns the group ID of this animal group entry.
	 *
	 * @return the group ID of this animal group entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this animal group entry.
	 *
	 * @param groupId the group ID of this animal group entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this animal group entry.
	 *
	 * @return the company ID of this animal group entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this animal group entry.
	 *
	 * @param companyId the company ID of this animal group entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this animal group entry.
	 *
	 * @return the user ID of this animal group entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this animal group entry.
	 *
	 * @param userId the user ID of this animal group entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this animal group entry.
	 *
	 * @return the user uuid of this animal group entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this animal group entry.
	 *
	 * @param userUuid the user uuid of this animal group entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this animal group entry.
	 *
	 * @return the user name of this animal group entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this animal group entry.
	 *
	 * @param userName the user name of this animal group entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this animal group entry.
	 *
	 * @return the create date of this animal group entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this animal group entry.
	 *
	 * @param createDate the create date of this animal group entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this animal group entry.
	 *
	 * @return the modified date of this animal group entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this animal group entry.
	 *
	 * @param modifiedDate the modified date of this animal group entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the creator ID of this animal group entry.
	 *
	 * @return the creator ID of this animal group entry
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this animal group entry.
	 *
	 * @param creatorId the creator ID of this animal group entry
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the customer ID of this animal group entry.
	 *
	 * @return the customer ID of this animal group entry
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this animal group entry.
	 *
	 * @param customerId the customer ID of this animal group entry
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the name of this animal group entry.
	 *
	 * @return the name of this animal group entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this animal group entry.
	 *
	 * @param name the name of this animal group entry
	 */
	public void setName(String name);

	/**
	 * Returns the description of this animal group entry.
	 *
	 * @return the description of this animal group entry
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this animal group entry.
	 *
	 * @param description the description of this animal group entry
	 */
	public void setDescription(String description);

	@Override
	public AnimalGroupEntry cloneWithOriginalValues();

}