/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.sample.pet.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DogEntry service. Represents a row in the &quot;DG_DOG&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.sample.pet.service.model.impl.DogEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.sample.pet.service.model.impl.DogEntryImpl</code>.
 * </p>
 *
 * @author khoavu
 * @see DogEntry
 * @generated
 */
@ProviderType
public interface DogEntryModel
	extends BaseModel<DogEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a dog entry model instance should use the {@link DogEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this dog entry.
	 *
	 * @return the primary key of this dog entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this dog entry.
	 *
	 * @param primaryKey the primary key of this dog entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this dog entry.
	 *
	 * @return the uuid of this dog entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this dog entry.
	 *
	 * @param uuid the uuid of this dog entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the external reference code of this dog entry.
	 *
	 * @return the external reference code of this dog entry
	 */
	@AutoEscape
	public String getExternalReferenceCode();

	/**
	 * Sets the external reference code of this dog entry.
	 *
	 * @param externalReferenceCode the external reference code of this dog entry
	 */
	public void setExternalReferenceCode(String externalReferenceCode);

	/**
	 * Returns the dog ID of this dog entry.
	 *
	 * @return the dog ID of this dog entry
	 */
	public long getDogId();

	/**
	 * Sets the dog ID of this dog entry.
	 *
	 * @param dogId the dog ID of this dog entry
	 */
	public void setDogId(long dogId);

	/**
	 * Returns the group ID of this dog entry.
	 *
	 * @return the group ID of this dog entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this dog entry.
	 *
	 * @param groupId the group ID of this dog entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this dog entry.
	 *
	 * @return the company ID of this dog entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this dog entry.
	 *
	 * @param companyId the company ID of this dog entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this dog entry.
	 *
	 * @return the user ID of this dog entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this dog entry.
	 *
	 * @param userId the user ID of this dog entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this dog entry.
	 *
	 * @return the user uuid of this dog entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this dog entry.
	 *
	 * @param userUuid the user uuid of this dog entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this dog entry.
	 *
	 * @return the user name of this dog entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this dog entry.
	 *
	 * @param userName the user name of this dog entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this dog entry.
	 *
	 * @return the create date of this dog entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this dog entry.
	 *
	 * @param createDate the create date of this dog entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this dog entry.
	 *
	 * @return the modified date of this dog entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this dog entry.
	 *
	 * @param modifiedDate the modified date of this dog entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the creator ID of this dog entry.
	 *
	 * @return the creator ID of this dog entry
	 */
	public long getCreatorId();

	/**
	 * Sets the creator ID of this dog entry.
	 *
	 * @param creatorId the creator ID of this dog entry
	 */
	public void setCreatorId(long creatorId);

	/**
	 * Returns the customer ID of this dog entry.
	 *
	 * @return the customer ID of this dog entry
	 */
	public long getCustomerId();

	/**
	 * Sets the customer ID of this dog entry.
	 *
	 * @param customerId the customer ID of this dog entry
	 */
	public void setCustomerId(long customerId);

	/**
	 * Returns the name of this dog entry.
	 *
	 * @return the name of this dog entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this dog entry.
	 *
	 * @param name the name of this dog entry
	 */
	public void setName(String name);

	/**
	 * Returns the title of this dog entry.
	 *
	 * @return the title of this dog entry
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this dog entry.
	 *
	 * @param title the title of this dog entry
	 */
	public void setTitle(String title);

	/**
	 * Returns the weight of this dog entry.
	 *
	 * @return the weight of this dog entry
	 */
	public double getWeight();

	/**
	 * Sets the weight of this dog entry.
	 *
	 * @param weight the weight of this dog entry
	 */
	public void setWeight(double weight);

	/**
	 * Returns the color of this dog entry.
	 *
	 * @return the color of this dog entry
	 */
	@AutoEscape
	public String getColor();

	/**
	 * Sets the color of this dog entry.
	 *
	 * @param color the color of this dog entry
	 */
	public void setColor(String color);

	/**
	 * Returns the status of this dog entry.
	 *
	 * @return the status of this dog entry
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this dog entry.
	 *
	 * @param status the status of this dog entry
	 */
	public void setStatus(String status);

	/**
	 * Returns the status date of this dog entry.
	 *
	 * @return the status date of this dog entry
	 */
	public Date getStatusDate();

	/**
	 * Sets the status date of this dog entry.
	 *
	 * @param statusDate the status date of this dog entry
	 */
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the animal group ID of this dog entry.
	 *
	 * @return the animal group ID of this dog entry
	 */
	public long getAnimalGroupId();

	/**
	 * Sets the animal group ID of this dog entry.
	 *
	 * @param animalGroupId the animal group ID of this dog entry
	 */
	public void setAnimalGroupId(long animalGroupId);

	@Override
	public DogEntry cloneWithOriginalValues();

}