/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.sample.animal.service.model.impl;

import com.dogoo.sample.animal.service.model.AnimalCategoryEntry;
import com.dogoo.sample.animal.service.model.AnimalCategoryEntryModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AnimalCategoryEntry service. Represents a row in the &quot;DG_ANIMAL_CATE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AnimalCategoryEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AnimalCategoryEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnimalCategoryEntryImpl
 * @generated
 */
public class AnimalCategoryEntryModelImpl
	extends BaseModelImpl<AnimalCategoryEntry>
	implements AnimalCategoryEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a animal category entry model instance should use the <code>AnimalCategoryEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DG_ANIMAL_CATE";

	public static final Object[][] TABLE_COLUMNS = {
		{"ID", Types.BIGINT}, {"NAME", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("NAME", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DG_ANIMAL_CATE (ID LONG not null primary key,NAME VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table DG_ANIMAL_CATE";

	public static final String ORDER_BY_JPQL =
		" ORDER BY animalCategoryEntry.animalId ASC";

	public static final String ORDER_BY_SQL = " ORDER BY DG_ANIMAL_CATE.ID ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ANIMALID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AnimalCategoryEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _animalId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAnimalId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _animalId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AnimalCategoryEntry.class;
	}

	@Override
	public String getModelClassName() {
		return AnimalCategoryEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AnimalCategoryEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AnimalCategoryEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnimalCategoryEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AnimalCategoryEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AnimalCategoryEntry, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AnimalCategoryEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AnimalCategoryEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AnimalCategoryEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AnimalCategoryEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, AnimalCategoryEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			AnimalCategoryEntry.class.getClassLoader(),
			AnimalCategoryEntry.class, ModelWrapper.class);

		try {
			Constructor<AnimalCategoryEntry> constructor =
				(Constructor<AnimalCategoryEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<AnimalCategoryEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AnimalCategoryEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AnimalCategoryEntry, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<AnimalCategoryEntry, Object>>();
		Map<String, BiConsumer<AnimalCategoryEntry, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<AnimalCategoryEntry, ?>>();

		attributeGetterFunctions.put(
			"animalId", AnimalCategoryEntry::getAnimalId);
		attributeSetterBiConsumers.put(
			"animalId",
			(BiConsumer<AnimalCategoryEntry, Long>)
				AnimalCategoryEntry::setAnimalId);
		attributeGetterFunctions.put("name", AnimalCategoryEntry::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<AnimalCategoryEntry, String>)
				AnimalCategoryEntry::setName);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getAnimalId() {
		return _animalId;
	}

	@Override
	public void setAnimalId(long animalId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_animalId = animalId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AnimalCategoryEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AnimalCategoryEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AnimalCategoryEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AnimalCategoryEntryImpl animalCategoryEntryImpl =
			new AnimalCategoryEntryImpl();

		animalCategoryEntryImpl.setAnimalId(getAnimalId());
		animalCategoryEntryImpl.setName(getName());

		animalCategoryEntryImpl.resetOriginalValues();

		return animalCategoryEntryImpl;
	}

	@Override
	public AnimalCategoryEntry cloneWithOriginalValues() {
		AnimalCategoryEntryImpl animalCategoryEntryImpl =
			new AnimalCategoryEntryImpl();

		animalCategoryEntryImpl.setAnimalId(
			this.<Long>getColumnOriginalValue("ID"));
		animalCategoryEntryImpl.setName(
			this.<String>getColumnOriginalValue("NAME"));

		return animalCategoryEntryImpl;
	}

	@Override
	public int compareTo(AnimalCategoryEntry animalCategoryEntry) {
		long primaryKey = animalCategoryEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AnimalCategoryEntry)) {
			return false;
		}

		AnimalCategoryEntry animalCategoryEntry = (AnimalCategoryEntry)object;

		long primaryKey = animalCategoryEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AnimalCategoryEntry> toCacheModel() {
		AnimalCategoryEntryCacheModel animalCategoryEntryCacheModel =
			new AnimalCategoryEntryCacheModel();

		animalCategoryEntryCacheModel.animalId = getAnimalId();

		animalCategoryEntryCacheModel.name = getName();

		String name = animalCategoryEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			animalCategoryEntryCacheModel.name = null;
		}

		return animalCategoryEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AnimalCategoryEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AnimalCategoryEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnimalCategoryEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AnimalCategoryEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AnimalCategoryEntry, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AnimalCategoryEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AnimalCategoryEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AnimalCategoryEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AnimalCategoryEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private long _animalId;
	private String _name;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<AnimalCategoryEntry, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AnimalCategoryEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("ID", _animalId);
		_columnOriginalValues.put("NAME", _name);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("ID", "animalId");
		attributeNames.put("NAME", "name");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("ID", 1L);

		columnBitmasks.put("NAME", 2L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AnimalCategoryEntry _escapedModel;

}