/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.sample.animal.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AnimalCategoryEntry service. Represents a row in the &quot;DG_ANIMAL_CATE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.sample.animal.service.model.impl.AnimalCategoryEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.sample.animal.service.model.impl.AnimalCategoryEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnimalCategoryEntry
 * @generated
 */
@ProviderType
public interface AnimalCategoryEntryModel
	extends BaseModel<AnimalCategoryEntry> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a animal category entry model instance should use the {@link AnimalCategoryEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this animal category entry.
	 *
	 * @return the primary key of this animal category entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this animal category entry.
	 *
	 * @param primaryKey the primary key of this animal category entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the animal ID of this animal category entry.
	 *
	 * @return the animal ID of this animal category entry
	 */
	public long getAnimalId();

	/**
	 * Sets the animal ID of this animal category entry.
	 *
	 * @param animalId the animal ID of this animal category entry
	 */
	public void setAnimalId(long animalId);

	/**
	 * Returns the name of this animal category entry.
	 *
	 * @return the name of this animal category entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this animal category entry.
	 *
	 * @param name the name of this animal category entry
	 */
	public void setName(String name);

	@Override
	public AnimalCategoryEntry cloneWithOriginalValues();

}